### ISSUE TITLE
Outdated links for Streams

### ISSUE THREAD

**Issue by saqimtiaz** [Marxsal/tw-resources#2]
`Streams (LI2)` tiddler is the only one correct with an up to date description and URL but it is not the one used for the links aggregator.

The following have an outdated description and URL:
`Streams (NAV3)`
`Streams (WRT3)`

**Comment by Marxsal** [comment]
Actually, Streams (LI2) was (is) being used. The interface doesn't show you the title so you have to compare by description. I've removed the duplicate Streams (NAV3). Streams (WRT3) wasn't being used -- only items marked $:/tags/Link get used by the aggregator. I retain old records in case of error, but will eventually purge them.

I made an extensive effort to remove duplicates _by url_, but removing duplicates _by concept_ is another thing.

**Comment by saqimtiaz** [comment]
Thank you.
