### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by trumad** [Marxsal/tw-resources#3]
This link is broken: [https://akhater.github.io/drift#Example%3A%20Spoiler](https://links.tiddlywiki.com/urls/b91195bd372cd121e5d9)

Luckily, I found it on wayback, if you want to replace it: https://web.archive.org/web/20211014222710/https://akhater.github.io/drift/#Example%3A%20Spoiler

**Comment by Marxsal** [comment]
Thanks! Updated.
